AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-Function
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: Function
      CodeUri: src/Function
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - SNSPublishMessagePolicy:
            TopicName: !If
              - TopicUseExistingResource
              - !GetAtt TopicExistingResource.TopicName
              - !GetAtt Topic.TopicName
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Environment:
        Variables:
          TOPIC_NAME: !If
            - TopicUseExistingResource
            - !GetAtt TopicExistingResource.TopicName
            - !GetAtt Topic.TopicName
          TOPIC_ARN: !If
            - TopicUseExistingResource
            - !Ref TopicExistingResource
            - !Ref Topic
    Condition: FunctionCreateNewResource
  FunctionExistingResource:
    Type: Custom::StackeryExistingResource
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:stackery-agent-commander
      Type: function
      Data: arn:aws:lambda:us-east-2:736111956127:function:RedditBot
    Condition: FunctionUseExistingResource
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-Topic
    Condition: TopicCreateNewResource
  TopicExistingResource:
    Type: Custom::StackeryExistingResource
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:stackery-agent-commander
      Type: topic
      Data: arn:aws:sns:us-east-2:736111956127:HotCookingPosts
    Condition: TopicUseExistingResource
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
Conditions:
  FunctionCreateNewResource: !Equals
    - 'false'
    - 'true'
  FunctionUseExistingResource: !Not
    - Condition: FunctionCreateNewResource
  TopicCreateNewResource: !Equals
    - 'false'
    - 'true'
  TopicUseExistingResource: !Not
    - Condition: TopicCreateNewResource